"""Parse all BibTeX files and generate Markdown for each entry."""

import glob
import os

from hooks.short import parse_entry, write_entry

WARN = "<!-- DO NOT EDIT THIS FILE (automatically generated by bibgen.py) -->"


def reformat_authors(author_string):
    """Convert author string to "First Last" format, separated by commas."""
    authors = author_string.split(" and ")
    reformatted = []
    for author in authors:
        if "," in author:
            last, first = [part.strip() for part in author.split(",", 1)]
            reformatted.append(f"{first} {last}")
        else:
            # Already in "First Last" format
            reformatted.append(author.strip())
    return ", ".join(reformatted)


def bib2md(path, entry):
    """Generate a Markdown file for the entry."""

    # Extract the most common fields
    title = entry.fields_dict["title"].value
    author = entry.fields_dict["author"].value
    year = entry.fields_dict["year"].value
    source = ""
    for fkey in ["booktitle", "journal", "publisher", "howpublished", "url"]:
        if fkey in entry.fields_dict:
            source = entry.fields_dict[fkey].value
            break

    # Create a reference format string
    author = reformat_authors(author)
    if source:
        source = f"*{source}*."
        if entry.entry_type.startswith("in"):
            source = "In " + source
    ref = f"{author}. ({year}). {title}. {source}"

    # Rename files to match the key
    name = os.path.basename(path)
    if name != entry.key + ".bib":
        new_name = entry.key + ".bib"
        new_path = path[:-len(name)] + new_name
        os.rename(path, new_path)
        md_path = path[:-3] + "md"
        if os.path.exists(md_path):
            os.rename(md_path, new_path[:-3] + "md")
        path = new_path
        name = new_name

    # Generate corresponding Markdown file
    with open(path[:-3] + "md", "w") as file:
        file.write("---\nhide:\n  - toc\n---\n\n")
        file.write(WARN + "\n\n")
        file.write(f"# {title}\n\n")
        file.write(f"**Reference:** {ref}\n\n")
        file.write('<div class="grid" markdown="1">\n\n')
        file.write(f"**Entry Key:** `#!tex \\cite{{{entry.key}}}`\n\n")
        file.write(f"**Entry Type:** `@{entry.entry_type}`\n\n")
        file.write("</div>\n")
        write_entry(entry, file)


def main():
    """Find and parse every bib file."""
    for path in glob.glob("docs/research/**/*.bib", recursive=True):
        print(path)
        entry = parse_entry(path)
        bib2md(path, entry)


if __name__ == "__main__":
    main()
